    name: Deploy .NET Core to GKE

    on:
      push:
        branches:
          - main

    env:
      DOCKER_IMAGE_NAME: your-dockerhub-username/your-repo-name
      GKE_CLUSTER: your-gke-cluster-name
      GKE_ZONE: your-gke-cluster-zone
      DEPLOYMENT_NAME: your-app-deployment-name

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

         