name: GCP .NET Core CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  image: gcpsantanubhunia/dotnetapp:v4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: $env.image

  # Optional: Add a deployment job if you want to deploy to a specific environment
  # deploy:
  #   needs: build-and-test # Ensures deployment only runs after successful build and tests
  #   runs-on: ubuntu-latest
  #   environment: Production # Example environment
  #   steps:
  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'your-app-name'
  #         slot-name: 'production'
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Store sensitive data in GitHub Secrets
  #         package: './path/to/your/publish/output' # Path to your published application
