name: Deploy to AKS

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Or configure OIDC
     
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/your-app:latest
          file: ./Dockerfile

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: dotnetappRG
          cluster-name: dotnetappakscluster

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: ${{ secrets.ACR_NAME }}.azurecr.io/your-app:latest