name: Deploy to AKS

on:
  push:
    branches:
      - main
env:
  IMAGE: gcr.io/${{ secrets.GCE_PROJECT }}/dotnetapp:v12

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Or configure OIDC
     
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.ACR_NAME }}.azurecr.io/dotnetapp:latest
      #     file: ./Dockerfile
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: dotnetappRG
          cluster-name: dotnetappakscluster

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            deployment.yaml
            service.yaml
          images: ${{ env.IMAGE }}